### Create ❶ 유저 생성
POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "jake",
  "password": "jake1234",
  "email": "jake@test.com"
}

### GetUser ❷ 유저 정보 찾기 
GET http://localhost:3000/user/getUser/jake@test.com


### Update User ❸ 유저 정보 업데이트 
PUT http://localhost:3000/user/update/jake@test.com
content-type: application/json

{
  "email": "jake@test.com",
  "username": "jake2",
  "password": "jake12345"
}

### Delete User  ❹ 유저 삭제 
DELETE http://localhost:3000/user/delete/jake@test.com

### 잘못된 이메일을 입력한 경우 
POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "jake2",
  "password": "jake12345",
  "email": "jake-test"
}